// auth
export const FETCH_USER = 'FETCH_USER';
export const AUTHORIZED = 'AUTHORIZED';
export const UNAUTHORIZED = 'UNAUTHORIZED';
// artist
export const RECEIVE_ARTIST_DATA = 'RECEIVE_ARTIST_DATA';
// system
export const SHOW_GLOBAL_SPINNER = 'SHOW_GLOBAL_SPINNER';
export const HIDE_GLOBAL_SPINNER = 'HIDE_GLOBAL_SPINNER';
export const PUSH_MESSAGE = 'PUSH_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';

export const RECEIVE_SONGS = 'RECEIVE_SONGS';
// playlist
export const RECEIVE_PLAY_LISTS = 'RECEIVE_PLAY_LISTS';
export const TOGGLE_PLAYLIST_SECTION = 'TOGGLE_PLAYLIST_SECTION';
export const SET_ACTIVE_INDEX = 'SET_ACTIVE_INDEX';
// player
export const SET_SONG = 'SET_SONG';
export const SET_PLAYLIST_DATA = 'SET_PLAYLIST_DATA';
export const TOGGLE_PLAY = 'TOGGLE_PLAY';
export const SET_ERROR_TRACK_ID = 'SET_ERROR_TRACK_ID';
export const LOADING_TRACK_STREAM = 'LOADING_TRACK_STREAM';
export const RECEIVE_TRACK_STREAM = 'RECEIVE_TRACK_STREAM';
// dialog
export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';